

class FooterMask(object):
	G_FOOTER_GROUP_STARTID				= 3100
	G_FOOTER_GROUP_IDGAP				= 10
	
	G_NUM_OF_FOOTER_ICON				= 4

	G_FOOTER_ICON_BACK_MASK				= 1 << 0
	G_FOOTER_ICON_OK_MASK				= 1 << 1
	G_FOOTER_ICON_SEARCH_MASK			= 1 << 2
	G_FOOTER_ICON_RECORD_MASK			= 1 << 3

	
'''
G_FOOTER_ICON_EXIT_MASK			= 1 << 1,
G_FOOTER_ICON_RED_MASK			= 1 << 4,
G_FOOTER_ICON_GREEN_MASK		= 1 << 5,
G_FOOTER_ICON_BLUE_MASK			= 1 << 6,
G_FOOTER_ICON_YELLOW_MASK		= 1 << 7,	
G_FOOTER_ICON_OPT_MASK			= 1 << 8,
G_FOOTER_ICON_PAUSE_MASK		= 1 << 9,
G_FOOTER_ICON_EDIT_MASK			= 1 << 10,	
G_FOOTER_ICON_PLAY_MASK			= 1 << 13,
G_FOOTER_ICON_MARK_MASK			= 1 << 14,
G_FOOTER_ICON_P_MASK			= 1 << 15,
G_FOOTER_ICON_NUM_0_MASK		= 1 << 16,
G_FOOTER_ICON_INFO_MASK			= 1 << 17,
G_FOOTER_ICON_DELETE_MASK		= 1 << 18,
G_FOOTER_ICON_FF_MASK			= 1 << 19,
G_FOOTER_ICON_REW_MASK			= 1 << 20,
G_FOOTER_ICON_REWFF_MASK		= 1 << 21,
G_FOOTER_ICON_NUMBER_MASK		= 1 << 22,
'''