class ElisEnum(object):
	E_TYPE_INVALID =      0		# ServiceType Invalid
	E_TYPE_TV =      1		# ServiceType TV
	E_TYPE_RADIO =      2		# ServiceType Radio
	E_TYPE_DATA =      3		# ServiceType Data
	E_MODE_ALL =      0		# ZappingMode ALL
	E_MODE_FAVORITE =      1		# ZappingMode Favorite
	E_MODE_NETWORK =      2		# ZappingMode Network
	E_MODE_SATELLITE =      3		# ZappingMode Satellite
	E_MODE_CAS =      4		# ZappingMode CAS
	E_SORT_BY_DEFAULT =      0		# SortingMode Default
	E_SORT_BY_ALPHABET =      1		# SortingMode Alphabet
	E_SORT_BY_CARRIER =      2		# SortingMode Carrier
	E_SORT_BY_NUMBER =      3		# SortingMode Number
	E_SORT_BY_HD =      4		# SortingMode HD
	E_LNB_HORIZONTAL =      0		# Transponder  Polarization Horizontal
	E_LNB_VERTICAL =      1		# Transponder  Polarization Vertical
	E_LNB_LEFT =      2		# Transponder  Polarization Left
	E_LNB_RIGHT =      3		# Transponder  Polarization Right
	E_FEC_UNDEFINED =      0		# Transponder  FECMode Undefined
	E_DVBS_1_2 =      1		# Transponder  FECMode DVBS 1_2
	E_DVBS_2_3 =      2		# Transponder  FECMode DVBS 2_3
	E_DVBS_3_4 =      3		# Transponder  FECMode DVBS 3_4
	E_DVBS_5_6 =      4		# Transponder  FECMode DVBS 5_6
	E_DVBS_7_8 =      5		# Transponder  FECMode DVBS 7_8
	E_DVBS2_QPSK_1_2 =      6		# Transponder  FECMode DVBS2 QPSK 1_2
	E_DVBS2_QPSK_3_5 =      7		# Transponder  FECMode DVBS2 QPSK 3_5
	E_DVBS2_QPSK_2_3 =      8		# Transponder  FECMode DVBS2 QPSK 2_3
	E_DVBS2_QPSK_3_4 =      9		# Transponder  FECMode DVBS2 QPSK 3_4
	E_DVBS2_QPSK_4_5 =      10		# Transponder  FECMode DVBS2 QPSK 4_5
	E_DVBS2_QPSK_5_6 =      11		# Transponder  FECMode DVBS2 QPSK 5_6
	E_DVBS2_QPSK_8_9 =      12		# Transponder  FECMode DVBS2 QPSK 8_9
	E_DVBS2_QPSK_9_10 =      13		# Transponder  FECMode DVBS2 QPSK 9_10
	E_DVBS2_8PSK_3_5 =      14		# Transponder  FECMode DVBS2 8PSK 3_5
	E_DVBS2_8PSK_2_3 =      15		# Transponder  FECMode DVBS2 8PSK 2_3
	E_DVBS2_8PSK_3_4 =      16		# Transponder  FECMode DVBS2 8PSK 3_4
	E_DVBS2_8PSK_5_6 =      17		# Transponder  FECMode DVBS2 8PSK 5_6
	E_DVBS2_8PSK_8_9 =      18		# Transponder  FECMode DVBS2 8PSK 8_9
	E_DVBS2_8PSK_9_10 =      19		# Transponder  FECMode DVBS2 8PSK 9_10
	E_SAT_22KHZ_OFF =      0		# Satellite Config 22KHZ Off
	E_SAT_22KHZ_ON =      1		# Satellite Config 22KHZ On
	E_SWITCH_DISABLED =      0		# Diseqc Switch Disabled
	E_SWITCH_1OF4 =      1		# Diseqc Switch 1OF4
	E_SWITCH_2OF4 =      2		# Diseqc Switch 2OF4
	E_SWITCH_3OF4 =      3		# Diseqc Switch 3OF4
	E_SWITCH_4OF4 =      4		# Diseqc Switch 4OF4
	E_SWITCH_MINI_A =      5		# Diseqc Switch MINI_A
	E_SWITCH_MINI_B =      6		# Diseqc Switch MINI_B
	E_LNB_UNIVERSAL =      0		# LNB Type UNIVERSAL
	E_LNB_SINGLE =      1		# LNB Type SINGLE
	E_LNB_DUAL =      2		# LNB Type DUAL
	E_MOTORIZED_OFF =      0		# Diseqc Motor OFF
	E_MOTORIZED_ON =      1		# Diseqc Motor ON
	E_MOTORIZED_USALS =      2		# Diseqc Motor USALS
	E_SORT_LONGITUDE =      0		# Satelite Sort Mode LONGITUDE
	E_SORT_NAME =      1		# Satelite Sort Mode NAME
	E_SORT_INSERTED =      2		# Satelite Sort Mode INSERTED
	E_BAND_UNDEFINED =      0		# Satellite Band UNDEFINED
	E_BAND_KU =      1		# Satellite Band KU
	E_BAND_C =      2		# Satellite Band C
	E_MAX_EPG_REQUEST_COUNT =      128		# EPG MAX COUNT
	E_MODE_LIVE =      0		# Player Mode LIVE
	E_MODE_TIMESHIFT =      1		# Player Mode TIMESHIFT
	E_MODE_PVR =      2		# Player Mode PVR
	E_PLAYER_TIMESHIFT_START_PAUSE =      0		# Timeshift Play Mode PAUSE 	
	E_PLAYER_TIMESHIFT_START_REWIND =      1		# Timeshift Play Mode REWIND     
	E_PLAYER_TIMESHIFT_START_REPLAY =      2		# Timeshift Play Mode REPLAY     
	UNKNOWN =      0		# Language UNKNOWN
	E_ENGLISH =      1		# Language ENGLISH
	E_FRENCH =      2		# Language FRENCH
	E_DEUTSCH =      3		# Language DEUTSCH
	E_ITALIAN =      4		# Language ITALIAN
	E_SPANISH =      5		# Language SPANISH
	E_ARABIC =      6		# Language ARABIC
	E_GREEK =      7		# Language GREEK
	E_TURKISH =      8		# Language TURKISH
	E_DANISH =      9		# Language DANISH
	E_SWEDISH =      10		# Language SWEDISH
	E_NORWEGIAN =      11		# Language NORWEGIAN
	E_DUTCH =      12		# Language DUTCH
	E_RUSSIAN =      13		# Language RUSSIAN
	E_KOREAN =      14		# Language KOREAN
	E_FINNISH =      15		# Language FINNISH
	E_CZECH =      16		# Language CZECH
	E_POLISH =      17		# Language POLISH
	E_PORTUGUESE =      18		# Language PORTUGUESE
	E_DEFAULT_STEP =      1		# property Step
	E_DEFAULT_MAX =      0x7fffffff		# property Max
	E_FTA_CHANNEL =      0		# CAS ID FTA Channel
	E_MEDIAGUARD =      1<<0		# CAS ID MEDIAGUARD
	E_VIACCESS =      1<<1		# CAS ID VIACCESS
	E_NAGRA =      1<<2		# CAS ID NAGRA
	E_IRDETO =      1<<3		# CAS ID IRDETO
	E_CONAX =      1<<4		# CAS ID CONAX
	E_CRYPTOWORKS =      1<<5		# CAS ID CRYPTOWORKS
	E_NDS =      1<<6		# CAS ID NDS
	E_BETADIGITAL =      1<<7		# CAS ID BETADIGITAL
	E_OTHERS =      1<<15		# CAS ID OTHERS
	E_HasHDVideo =      1 << 0		# Channel Componets HD Video
	E_Has16_9Video =      1<<1		# Channel Componets 16_9 Video
	E_HasStereoAudio =      1<<2		# Channel Componets Stereo Audio
	E_HasMultichannelAudio =      1<<3		# Channel Componets Multi Channel Audio
	E_HasDolbyDigital =      1<<4		# Channel Componets DolbyDigital
	E_HasSubtitles =      1<<5		# Channel Componets Subtitles
	E_HasHardOfHearingAudio =      1<<6		# Channel Componets Hard of Hearing Audio
	E_HasHardOfHearingSub =      1<<7		# Channel Componets Hard of Hearing Sub
	E_HasVisuallyImpairedAudio =      1<<8		# Channel Componets Visually Impaired Audio
