# PRODUCT
PRODUCT_RUBY			=	0
PRODUCT_OSCAR			=	1

# TUNER TYPE
TUNER_TYPE_NONE			= -1
TUNER_TYPE_DVBS_SINGLE	= 0
TUNER_TYPE_DVBS_DUAL	= 1
TUNER_TYPE_DVBT			= 2
TUNER_TYPE_DVBC 		= 3
TUNER_TYPE_DVBTC		= 4